# Generated by Django 6.0.3 on 2026-03-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Furniture_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src", models.CharField(max_length=300)),
                ("title", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Living Spaces", "Living Spaces"),
                            ("Bedrooms", "Bedrooms"),
                            ("Kitchen", "Kitchen"),
                            ("Bathrooms", "Bathrooms"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
